### ISSUE TITLE
Have the bot automatically reference the FAQ in #discord-suggestions when a commonly asked question is asked

### ISSUE THREAD

**Issue by robotzurg** [MattBSG/MechaBowser#1]
## Double check duplicates
See the [Trello board](https://trello.com/b/2y9jL4mo/mecha-bowser) and make sure the change you are requesting is not already a card

## Update the following fields with the correct information
**Type of change:** feature

**Description:** Basically what the topic says, it should in theory delete the suggestion and DM the user who posted it the FAQ that corresponds to their question, to avoid overflowing the #discord-suggestions chat

**Images:** Put images here if needed

**Comment by MattBSG** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Have the bot automatically reference the FAQ in #discord-suggestions when a commonly asked question is asked](https://trello.com/c/0bakp41c/43-have-the-bot-automatically-reference-the-faq-in-discord-suggestions-when-a-commonly-asked-question-is-asked)
